name: "Connect4"

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'connect4|')
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Setup Gems
      run: |
        gem install octokit -N --silent

    - name: Play
      env:
        REPOSITORY: ${{ github.repository }}
        EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
      run: |
        ruby <<- EORUBY
          require './connect4/runner'
          
          Connect4::Runner.new(
            github_token: '${{ secrets.GITHUB_TOKEN }}',
            issue_number: ENV.fetch('EVENT_ISSUE_NUMBER'),
            issue_title: ENV.fetch('EVENT_ISSUE_TITLE'),
            repository: ENV.fetch('REPOSITORY'),
            user: ENV.fetch('EVENT_USER_LOGIN'),
          ).run
        EORUBY
